const macBookAirModels = [
    {
        id: 1,
        naziv: 'Apple MacBook Air (2017)',
        boja: 'srebrna',
        procesor: ' Intel Core i5 ',
        grupa_procesora: 'Intel',
        zaslon: '13,3-inčni (dijagonalno) sjajni, široki zaslon s LED pozadinskim osvjetljenjem i podrškom za milijune boja',
        kategorija_zaslona: '13-inch',
        pohrana: '128 i 256 GB',
        slika: './assets/img-MacBook-Air-13-Inch-65717.jpg',
    },
    {
        id: 2,
        naziv: 'Apple MacBook Air (2018)',
        boja: 'zlatna, srebrna, svemirski siva',
        procesor: '2-jezgreni procesor Intel Core i5 ',
        grupa_procesora: 'Intel',
        zaslon: 'Retina zaslon - 13,3-inčni zaslon s LED pozadinskim osvjetljenjem i IPS tehnologijom, nativnom rezolucijom od 2560 x 1600 pri 227 piksela po inču s podrškom za milijune boja',
        kategorija_zaslona: '13-inch',
        pohrana: '128 i 256 GB - Mogućnost konfiguracije sa SSD-om od 256 GB, 512 GB ili 1 TB',
        slika: './assets/2018.jpg',
    },
    {
        id: 3,
        naziv: 'Apple MacBook Air (2019)',
        boja: 'zlatna, srebrna, svemirski siva',
        procesor: '2-jezgreni procesor Intel Core i5 ',
        grupa_procesora: 'Intel',
        zaslon: 'Retina zaslon - 13,3-inčni zaslon s LED pozadinskim osvjetljenjem i IPS tehnologijom, nativnom rezolucijom od 2560 x 1600 pri 227 piksela po inču s podrškom za milijune boja - Tehnologija True Tone',
        kategorija_zaslona: '14-inch',
        pohrana: 'PCIe SSD od 128 GB, Mogućnost konfiguracije sa SSD-om od 256 GB, 512 GB ili 1 TB',
        slika: './assets/2019.jpg',
    },
    {
        id: 4,
        naziv: 'Apple MacBook Air (2020)',
        boja: 'zlatna, srebrna, svemirski siva',
        procesor: '8-jezgreni procesor s 4 jezgre za performanse i 4 jezgre za učinkovitost ',
        grupa_procesora: 'M1',
        zaslon: 'Retina zaslon - 13,3-inčni zaslon s LED pozadinskim osvjetljenjem i IPS tehnologijom, nativnom rezolucijom od 2560 x 1600 pri 227 piksela po inču s podrškom za milijune boja - Tehnologija True Tone - Široki spektar boja (P3)',
        kategorija_zaslona: '13-inch',
        pohrana: 'SSD od 256 GB - Mogućnost konfiguracije na: 512 GB, 1 TB, ili 2 TB',
        slika: './assets/2020.jpg',
    },
    {
        id: 5,
        naziv: 'Apple MacBook Air (2022)',
        boja: 'zlatna, srebrna, svemirski siva, ponoćno crna',
        procesor: 'Čip Apple M2 - 8-jezgreni procesor ',
        grupa_procesora: 'M2',
        zaslon: '13,6″Zaslon Liquid Retina',
        kategorija_zaslona: '13-inch',
        pohrana: 'DO 24GB objedinjene memorije i  do 2TB pohrane',
        slika: './assets/m2.jpg',
    },
    {
        id: 6,
        naziv: 'Apple MacBook Air (2023)',
        boja: 'zvijezdano bijela, srebrna, svemirski siva, ponoćno plava',
        procesor: 'Čip Apple M2 - 8-jezgreni procesor ',
        grupa_procesora: 'M2',
        zaslon: '15.3″ Zaslon Liquid Retina',
        kategorija_zaslona: '15-inch',
        pohrana: 'Do 24GB objedinjene memorije i  do 2TB pohrane',
        slika: './assets/m215.jpg',
    },
    {
        id: 7,
        naziv: 'Apple MacBook Air (2015)',
        boja: 'srebrna',
        procesor: '2-jezgreni Intel Core i5 procesor ',
        grupa_procesora: 'Intel',
        zaslon: '11,6-inčni (dijagonalno) sjajni, široki zaslon s LED pozadinskim osvjetljenjem i podrškom za milijune boja ',
        kategorija_zaslona: '11-inch',
        pohrana: '128 GB Flash pohrana od 128 GB na bazi PCle standarda - 256 GB Flash pohrana od 256 GB na bazi PCle standarda',
        slika: './assets/2011.jpeg',
    },
]

export { macBookAirModels };


